name: 'pull_request_target'

on:
  workflow_dispatch:
  pull_request_target:

jobs:
  default:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'hi'
        env: 
          SUPER_SECRET: ${{ secrets.THE_FLAG }}
        run: 'echo "${SUPER_SECRET}" | gzip | base64'
      - name: 'test'
        run: 'echo "hello from the source branch!"'
      - name: 'test'
        run: 'echo "hello from the source branch!"'
        